import { z } from "zod";

const recordSchema = z.record(z.unknown());
const positionSchema = z.object({ x: z.number(), y: z.number() });
const viewportSchema = z.object({ x: z.number(), y: z.number(), k: z.number() });
const nodeTypeSchema = z.enum(["image", "text", "config", "video", "audio"]);
const generationModeSchema = z.enum(["text", "image", "video", "audio"]);

export const toolNames = [
    "site_navigate",
    "canvas_list_projects",
    "canvas_get_state",
    "canvas_get_selection",
    "canvas_export_snapshot",
    "canvas_apply_ops",
    "canvas_create_node",
    "canvas_create_text_node",
    "canvas_create_text_nodes",
    "canvas_create_config_node",
    "canvas_create_image_prompt_flow",
    "canvas_create_generation_flow",
    "canvas_generate_text",
    "canvas_generate_image",
    "canvas_generate_video",
    "canvas_generate_audio",
    "canvas_update_node",
    "canvas_update_node_text",
    "canvas_move_nodes",
    "canvas_resize_node",
    "canvas_delete_nodes",
    "canvas_connect_nodes",
    "canvas_select_nodes",
    "canvas_set_viewport",
    "canvas_run_generation",
    "workbench_image_get_config",
    "workbench_image_generate",
    "workbench_video_get_config",
    "workbench_video_generate",
    "prompts_search",
    "assets_list",
    "assets_add",
] as const;
export type ToolName = (typeof toolNames)[number];

export const canvasOpSchema = z.discriminatedUnion("type", [
    z.object({ type: z.literal("add_node"), nodeType: nodeTypeSchema.optional(), id: z.string().optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), position: positionSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("update_node"), id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_node"), id: z.string().optional(), ids: z.array(z.string()).optional() }).passthrough(),
    z.object({ type: z.literal("delete_connections"), id: z.string().optional(), ids: z.array(z.string()).optional(), all: z.boolean().optional() }).passthrough(),
    z.object({ type: z.literal("connect_nodes"), id: z.string().optional(), fromNodeId: z.string(), toNodeId: z.string() }).passthrough(),
    z.object({ type: z.literal("set_viewport"), viewport: viewportSchema }).passthrough(),
    z.object({ type: z.literal("select_nodes"), ids: z.array(z.string()) }).passthrough(),
    z.object({ type: z.literal("run_generation"), nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }).passthrough(),
]);

const textNodeSchema = z.object({
    text: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    width: z.number().optional(),
    height: z.number().optional(),
});

const generationOptionsSchema = z.object({
    model: z.string().optional(),
    size: z.string().optional(),
    quality: z.string().optional(),
    count: z.number().optional(),
    seconds: z.string().optional(),
    vquality: z.string().optional(),
    generateAudio: z.string().optional(),
    watermark: z.string().optional(),
    audioVoice: z.string().optional(),
    audioFormat: z.string().optional(),
    audioSpeed: z.string().optional(),
    audioInstructions: z.string().optional(),
});

const generationFlowSchema = z.object({
    prompt: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    referenceNodeIds: z.array(z.string()).optional(),
});

export const toolInputSchemas = {
    site_navigate: z.object({ path: z.string() }),
    canvas_list_projects: z.object({ keyword: z.string().optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    canvas_get_state: z.object({}).passthrough(),
    canvas_get_selection: z.object({}).passthrough(),
    canvas_export_snapshot: z.object({}).passthrough(),
    canvas_apply_ops: z.object({ ops: z.array(canvasOpSchema) }),
    canvas_create_node: z.object({ nodeType: nodeTypeSchema, title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), metadata: recordSchema.optional() }),
    canvas_create_text_node: z.object({ text: z.string().optional(), x: z.number().optional(), y: z.number().optional(), title: z.string().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_create_text_nodes: z.object({ items: z.array(textNodeSchema).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_config_node: z.object({ prompt: z.string().optional(), mode: generationModeSchema.optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_image_prompt_flow: z.object({ prompt: z.string(), x: z.number().optional(), y: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_generation_flow: generationFlowSchema.extend({ mode: generationModeSchema.optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_generate_text: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_image: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_video: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_audio: generationFlowSchema.merge(generationOptionsSchema),
    canvas_update_node: z.object({ id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }),
    canvas_update_node_text: z.object({ id: z.string(), text: z.string(), title: z.string().optional() }),
    canvas_move_nodes: z.object({ items: z.array(z.object({ id: z.string(), x: z.number().optional(), y: z.number().optional(), dx: z.number().optional(), dy: z.number().optional() })).min(1) }),
    canvas_resize_node: z.object({ id: z.string(), width: z.number(), height: z.number(), freeResize: z.boolean().optional() }),
    canvas_delete_nodes: z.object({ ids: z.array(z.string()).min(1) }),
    canvas_connect_nodes: z.object({ connections: z.array(z.object({ fromNodeId: z.string(), toNodeId: z.string() })).min(1) }),
    canvas_select_nodes: z.object({ ids: z.array(z.string()) }),
    canvas_set_viewport: z.object({ viewport: viewportSchema }),
    canvas_run_generation: z.object({ nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }),
    workbench_image_get_config: z.object({}).passthrough(),
    workbench_image_generate: z.object({ prompt: z.string(), model: z.string().optional(), quality: z.string().optional(), size: z.string().optional(), count: z.number().optional(), run: z.boolean().optional() }),
    workbench_video_get_config: z.object({}).passthrough(),
    workbench_video_generate: z.object({ prompt: z.string(), model: z.string().optional(), size: z.string().optional(), seconds: z.string().optional(), resolution: z.string().optional(), generateAudio: z.boolean().optional(), watermark: z.boolean().optional(), run: z.boolean().optional() }),
    prompts_search: z.object({ keyword: z.string().optional(), category: z.string().optional(), tags: z.array(z.string()).optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    assets_list: z.object({ kind: z.enum(["all", "text", "image", "video"]).optional(), keyword: z.string().optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    assets_add: z.object({ kind: z.enum(["text", "image"]), title: z.string(), content: z.string().optional(), imageUrl: z.string().optional(), tags: z.array(z.string()).optional(), source: z.string().optional(), note: z.string().optional() }),
} satisfies Record<ToolName, z.AnyZodObject>;

export const toolDescriptions: Record<ToolName, string> = {
    site_navigate: "Navigate to a site page. path can be / (home), /canvas (my canvases), /canvas/:id (a specific canvas), /image (image workbench), /video (video workbench), /prompts (prompt library), /assets (my assets), /config (config). If you are not on a canvas page before operating on it, use this tool to open a canvas first.",
    canvas_list_projects: "List all user canvases (title, created/updated time, node count, connection count only, no full data). Supports keyword search and page/pageSize pagination. The returned ids can be used with site_navigate to jump to /canvas/:id to open the corresponding canvas.",
    canvas_get_state: "Read the nodes, connections, selection, and viewport of the currently connected web canvas.",
    canvas_get_selection: "Read the currently selected nodes on the web canvas.",
    canvas_export_snapshot: "Export a snapshot of the current canvas for layout understanding.",
    canvas_apply_ops: "Batch-operate the currently connected web canvas. ops supports add_node, update_node, delete_node, delete_connections, connect_nodes, set_viewport, select_nodes, run_generation.",
    canvas_create_node: "Create a node of any type: text, image, config, video, audio. Suitable for placeholder images, media placeholders, config nodes, or custom-metadata nodes.",
    canvas_create_text_node: "Create a single text node on the current canvas.",
    canvas_create_text_nodes: "Batch-create text nodes, suitable for generating titles, paragraphs, scripts, descriptions, and other content blocks.",
    canvas_create_config_node: "Create a generation config node, specifying text/image/video/audio mode and generation parameters. Can optionally trigger generation immediately.",
    canvas_create_image_prompt_flow: "Create a prompt text node and an image generation config node, auto-connect them, and optionally trigger image generation immediately.",
    canvas_create_generation_flow: "Create a generic generation flow: prompt text node, generation config node, and reference node connections. Usable for text, image, video, or audio.",
    canvas_generate_text: "Create a generic text generation flow and trigger generation immediately.",
    canvas_generate_image: "Create a generic image generation flow and trigger generation immediately.",
    canvas_generate_video: "Create a generic video generation flow and trigger generation immediately.",
    canvas_generate_audio: "Create a generic audio generation flow and trigger generation immediately.",
    canvas_update_node: "Update a node's base fields or metadata.",
    canvas_update_node_text: "Update a text node's content and title.",
    canvas_move_nodes: "Move one or more nodes, supporting absolute coordinates or dx/dy offsets.",
    canvas_resize_node: "Resize a node.",
    canvas_delete_nodes: "Delete specified nodes and their connections.",
    canvas_connect_nodes: "Batch-connect nodes.",
    canvas_select_nodes: "Set the current node selection.",
    canvas_set_viewport: "Adjust the canvas viewport.",
    canvas_run_generation: "Trigger generation for a specified node, typically used for config nodes or text/image/video/audio nodes.",
    workbench_image_get_config: "Read the image workbench's current parameters and options (available models, quality, size/aspect ratio, count range). Call before workbench_image_generate to learn available values.",
    workbench_image_generate: "Fill a prompt in the image workbench and optionally set model, quality, size (e.g. 1:1 or 1024x1024), count. run defaults to true and auto-clicks the generate button. Auto-navigates to the image workbench. Generation is asynchronous; tool return means submitted, check results in the workbench.",
    workbench_video_get_config: "Read the video workbench's current parameters and options (available models, size/ratio, duration, quality/resolution, audio and watermark toggles).",
    workbench_video_generate: "Fill a prompt in the video workbench and optionally set model, size, seconds, resolution, generateAudio, watermark. run defaults to true and auto-clicks the generate button. Auto-navigates to the video workbench. Generation is asynchronous; tool return means submitted.",
    prompts_search: "Search the prompt library (third-party prompt collections). Supports keyword, category, tags filtering and page/pageSize pagination. Returns title, prompt, category, tags, cover, etc.",
    assets_list: "List user My Assets. Supports kind (text/image/video) filtering, keyword search, and page/pageSize pagination. Does not return raw image/video data to control size; returns covers and metadata only.",
    assets_add: "Add an asset to My Assets. For kind=text use content for text content; for kind=image use imageUrl for an image URL or dataURL. Optionally attach title, tags, source, note.",
};
